In [1]:
import pandas as pd

# Direct download link
url = "https://drive.google.com/uc?id=1Mlu9r3afSGz5_02Y3wDJoQLpXszQXaIU"

# Load dataset
df = pd.read_csv(url, index_col="order_id")

# First 5 rows
print("First 5 rows:")
display(df.head())

# Last 5 rows
print("Last 5 rows:")
display(df.tail())

First 5 rows:

          customer_name   product  quantity  unit_price  order_date     status
order_id
1001      Alice Johnson    Laptop       1.0     85000.0  2024-01-15  delivered
1002          Bob Smith     Mouse       3.0       499.0  2024-01-16    pending
1003        Carol White   Monitor       2.0     15000.0         NaN  delivered
1004         Dave Brown  Keyboard       NaN      1200.0  2024-01-18  cancelled
1005          Eva Green    Laptop       1.0     85000.0  2024-01-19  delivered

Last 5 rows:

         customer_name   product  quantity  unit_price  order_date     status
order_id
1016       Paul Harris     Mouse       6.0       499.0  2024-01-30    pending
1017      Quinn Martin   Monitor       NaN     14500.0  2024-01-31  delivered
1018       Rachel King    Laptop       1.0     85000.0         NaN  delivered
1019        Sam Wright  Keyboard       3.0      1200.0  2024-02-01  cancelled
1020        Tina Baker   USB Hub       2.0       799.0  2024-02-02    pending

In [2]:
# Shape of dataset
print("Dataset Shape:", df.shape)

# Info about dataset
df.info()

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape: (20, 6)
<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     object
 5   status         20 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.1+ KB

Missing Values:
customer_name    0
product          0
quantity         4
unit_price       0
order_date       4
status           0
dtype: int64

In [3]:
# Statistical summary
summary = df.describe()
print(summary)

# Median unit_price
median_price = df["unit_price"].median()
print("\nMedian unit_price:", median_price)

        quantity    unit_price
count  16.000000     20.000000
mean    2.437500  20224.600000
std     1.504161  33573.389607
min     1.000000    499.000000
25%     1.000000    799.000000
50%     2.000000   2500.000000
75%     3.000000  14625.000000
max     6.000000  85000.000000

Median unit_price: 2500.0

In [4]:
df.tail()

         customer_name   product  quantity  unit_price  order_date     status
order_id
1016       Paul Harris     Mouse       6.0       499.0  2024-01-30    pending
1017      Quinn Martin   Monitor       NaN     14500.0  2024-01-31  delivered
1018       Rachel King    Laptop       1.0     85000.0         NaN  delivered
1019        Sam Wright  Keyboard       3.0      1200.0  2024-02-01  cancelled
1020        Tina Baker   USB Hub       2.0       799.0  2024-02-02    pending

#structer
Code Cell → Load dataset
Code Cell → Head & Tail

Code Cell → df.info(), df.shape, null check
Markdown Cell → Answer questions

Code Cell → df.describe()
Markdown Cell → Answer statistical questions

In [8]:
# dataset shape
df.shape

(20, 6)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     object
 5   status         20 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.1+ KB

In [10]:
df.isnull().sum()

customer_name    0
product          0
quantity         4
unit_price       0
order_date       4
status           0
dtype: int64

### Task 2 Answers

1. The dataset contains **(rows)** rows and **(columns)** columns.

2. Columns with missing values are:
(Check df.isnull().sum() output)

3. The column that needs data type conversion is **order_date**.

It should be converted using:

pd.to_datetime(df["order_date"])

In [11]:
df.describe()

        quantity    unit_price
count  16.000000     20.000000
mean    2.437500  20224.600000
std     1.504161  33573.389607
min     1.000000    499.000000
25%     1.000000    799.000000
50%     2.000000   2500.000000
75%     3.000000  14625.000000
max     6.000000  85000.000000

In [12]:
df["unit_price"].median()

2500.0